# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:



    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN


    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        main:
            pattern: ^/
            logout:       true
            anonymous:    true
            # activate different ways to authenticate

                        # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
                        #http_basic: ~

                        # https://symfony.com/doc/current/security/form_login_setup.html
                        #form_login: ~
        # disables authentication for assets and the profiler, adapt ir according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)\css\images\js)/
            security: false

    access_control:
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/, role: ROLE_ADMIN }